export const activesMock = [
  {
    symbol: "SQQQ",
    name: "ProShares UltraPro Short QQQ",
    change: 0.32,
    price: 11.65,
    changesPercentage: 2.8244,
  },
  {
    symbol: "SOXS",
    name: "Direxion Daily Semiconductor Bear 3X Shares",
    change: 0.09,
    price: 4.39,
    changesPercentage: 2.093,
  },
  {
    symbol: "SOUN",
    name: "SoundHound AI, Inc.",
    change: 0.06,
    price: 3.82,
    changesPercentage: 1.5957,
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    change: -0.5,
    price: 199.95,
    changesPercentage: -0.2494,
  },
  {
    symbol: "HTOO",
    name: "Fusion Fuel Green PLC",
    change: 1.08,
    price: 2.28,
    changesPercentage: 90,
  },
  {
    symbol: "SOXL",
    name: "Direxion Daily Semiconductor Bull 3X Shares",
    change: -0.78,
    price: 38.33,
    changesPercentage: -1.9944,
  },
  {
    symbol: "TQQQ",
    name: "ProShares UltraPro QQQ",
    change: -1.62,
    price: 57.41,
    changesPercentage: -2.7444,
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    change: -2.53,
    price: 499.48,
    changesPercentage: -0.504,
  },
  {
    symbol: "GOEV",
    name: "Canoo Inc.",
    change: -0.0046,
    price: 0.1409,
    changesPercentage: -3.1615,
  },
  {
    symbol: "AMBO",
    name: "Ambow Education Holding Ltd.",
    change: 0.162,
    price: 0.3,
    changesPercentage: 117.391,
  },
  {
    symbol: "FXI",
    name: "iShares China Large-Cap ETF",
    change: 0.31,
    price: 23.07,
    changesPercentage: 1.362,
  },
  {
    symbol: "TELL",
    name: "Tellurian Inc.",
    change: 0.071,
    price: 0.8915,
    changesPercentage: 8.6533,
  },
  {
    symbol: "PLTR",
    name: "Palantir Technologies Inc.",
    change: -0.97,
    price: 24.44,
    changesPercentage: -3.8174,
  },
  {
    symbol: "NKLA",
    name: "Nikola Corporation",
    change: -0.0101,
    price: 0.7399,
    changesPercentage: -1.3467,
  },
  {
    symbol: "MARA",
    name: "Marathon Digital Holdings, Inc.",
    change: -0.08,
    price: 26.94,
    changesPercentage: -0.2961,
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    change: -2.89,
    price: 173.87,
    changesPercentage: -1.635,
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    change: -3.94,
    price: 430.57,
    changesPercentage: -0.9068,
  },
  {
    symbol: "GGE",
    name: "Green Giant Inc.",
    change: 0.0037,
    price: 0.0452,
    changesPercentage: 8.9157,
  },
  {
    symbol: "SOFI",
    name: "SoFi Technologies, Inc.",
    change: -0.17,
    price: 8.36,
    changesPercentage: -1.993,
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    change: -0.45,
    price: 726.13,
    changesPercentage: -0.0619,
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    change: -1.55,
    price: 182.31,
    changesPercentage: -0.843,
  },
  {
    symbol: "HYG",
    name: "iShares iBoxx $ High Yield Corporate Bond ETF",
    change: -0.23,
    price: 76.91,
    changesPercentage: -0.2982,
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    change: -0.29,
    price: 169.51,
    changesPercentage: -0.1708,
  },
  {
    symbol: "FFIE",
    name: "Faraday Future Intelligent Electric Inc.",
    change: -0.0154,
    price: 0.0937,
    changesPercentage: -14.1155,
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000 ETF",
    change: -2.78,
    price: 201.66,
    changesPercentage: -1.3598,
  },
  {
    symbol: "NNOX",
    name: "Nano-X Imaging Ltd.",
    change: 3.45,
    price: 12.95,
    changesPercentage: 36.3158,
  },
  {
    symbol: "SNAP",
    name: "Snap Inc.",
    change: -0.43,
    price: 11.17,
    changesPercentage: -3.7069,
  },
  {
    symbol: "CPOP",
    name: "Pop Culture Group Co., Ltd",
    change: 1.37,
    price: 2.65,
    changesPercentage: 107.0313,
  },
  {
    symbol: "NU",
    name: "Nu Holdings Ltd.",
    change: -0.1,
    price: 10.36,
    changesPercentage: -0.956,
  },
  {
    symbol: "F",
    name: "Ford Motor Company",
    change: -0.22,
    price: 12.3,
    changesPercentage: -1.7572,
  },
  {
    symbol: "NIO",
    name: "NIO Inc.",
    change: 0.05,
    price: 6.14,
    changesPercentage: 0.821,
  },
  {
    symbol: "OPEN",
    name: "Opendoor Technologies Inc.",
    change: -0.35,
    price: 3,
    changesPercentage: -10.4478,
  },
  {
    symbol: "ROKU",
    name: "Roku, Inc.",
    change: -22.5,
    price: 72,
    changesPercentage: -23.8095,
  },
  {
    symbol: "XLF",
    name: "Financial Select Sector SPDR Fund",
    change: -0.14,
    price: 39.63,
    changesPercentage: -0.352,
  },
  {
    symbol: "LYFT",
    name: "Lyft, Inc.",
    change: -1.12,
    price: 17.91,
    changesPercentage: -5.8854,
  },
  {
    symbol: "WISA",
    name: "WiSA Technologies, Inc.",
    change: -0.0037,
    price: 0.0484,
    changesPercentage: -7.1017,
  },
  {
    symbol: "SPXS",
    name: "Direxion Daily S&P 500 Bear 3X Shares",
    change: 0.15,
    price: 10.13,
    changesPercentage: 1.503,
  },
  {
    symbol: "PHUN",
    name: "Phunware, Inc.",
    change: -0.0076,
    price: 0.299,
    changesPercentage: -2.4788,
  },
  {
    symbol: "EEM",
    name: "iShares MSCI Emerging Markets ETF",
    change: 0.19,
    price: 40.08,
    changesPercentage: 0.4763,
  },
  {
    symbol: "HOOD",
    name: "Robinhood Markets, Inc.",
    change: 0.58,
    price: 14,
    changesPercentage: 4.3219,
  },
  {
    symbol: "VALE",
    name: "Vale S.A.",
    change: 0.4,
    price: 13.63,
    changesPercentage: 3.0234,
  },
  {
    symbol: "LCID",
    name: "Lucid Group, Inc.",
    change: 0.08,
    price: 3.71,
    changesPercentage: 2.2039,
  },
  {
    symbol: "SMCI",
    name: "Super Micro Computer, Inc.",
    change: -200.68,
    price: 803.32,
    changesPercentage: -19.988,
  },
  {
    symbol: "CLSK",
    name: "CleanSpark, Inc.",
    change: 0.63,
    price: 17.86,
    changesPercentage: 3.6564,
  },
  {
    symbol: "DKNG",
    name: "DraftKings Inc.",
    change: 0.11,
    price: 44.57,
    changesPercentage: 0.2474,
  },
  {
    symbol: "COIN",
    name: "Coinbase Global, Inc.",
    change: 14.64,
    price: 180.31,
    changesPercentage: 8.8368,
  },
  {
    symbol: "BITF",
    name: "Bitfarms Ltd.",
    change: 0.13,
    price: 3.61,
    changesPercentage: 3.7356,
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    change: -0.54,
    price: 92.76,
    changesPercentage: -0.5788,
  },
  {
    symbol: "TZA",
    name: "Direxion Daily Small Cap Bear 3X Shares",
    change: 0.74,
    price: 19.33,
    changesPercentage: 3.9806,
  },
  {
    symbol: "SPXU",
    name: "ProShares UltraPro Short S&P500",
    change: 0.12,
    price: 7.54,
    changesPercentage: 1.6173,
  },
];
